final_society/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'E-House Care Admin Interface'
admin.site.site_title = 'E-House Care'
admin.site.intex_title = 'Database Management System'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('noticeboard', views.noticeboard, name='noticeboard'),
    path('complaint/', views.complaint, name='complaint'),
    path('staff/', views.staff, name='staff'),
    path('makenotice', views.makenotice, name='makenotice'),
    path('service', views.service, name='service'),
    path('searchbill', views.searchbill, name='searchbill'),
    path('<int:bill_id>/', views.viewbill, name='viewbill'),
    path('addvisitor', views.addvisitor, name='addvisitor'),
    path('otpfunc', views.otpfunc, name='otpfunc'),
    path('visitor', views.visitor, name='visitor'),
    path('bill/<int:bill_id>', views.viewbill, name='viewbill'),
    path('pay/<int:bill_id>', views.pay, name='pay'),
    path('test', views.test, name='test'),
    path('success' , views.success , name='success')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.db.models.fields import CharField, TextField, EmailField, IntegerField
from django.contrib.auth.models import User
from django.contrib.auth.models import UserManager
from datetime import datetime
import datetime
class MainPage(models.Model):
    society_name = CharField(max_length=200)
    society_about = TextField()

    def __str__(self):
        return self.society_name

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField()
    age = models.IntegerField(blank=True)
    flat_no = models.CharField(max_length=10)
    phone_number = models.IntegerField()

    def __str__(self):
        return str(self.flat_no)


class Notice(models.Model):
    header_notice = CharField(max_length=100)
    details_notice = TextField()

    def __str__(self):
        return self.header_notice

class Complaint(models.Model):
    contact_name = models.CharField(max_length=100)
    contact_email = models.EmailField()
    content = models.TextField()
    complaint_user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.contact_name)

class Staff(models.Model):
    staff_name = models.CharField(max_length=100)
    staff_email = models.EmailField()
    staff_phone = models.IntegerField()
    designation = models.CharField(max_length=100)
    about = models.TextField(null=True)
    image = models.ImageField(upload_to='main/images')
    def __str__(self):
        return str(self.designation)

class Visitor(models.Model):
    visitor_name = models.CharField(max_length=100)
    visitor_phone =  models.IntegerField()
    visiting_flat = models.CharField(max_length=100)
    visiting_date = models.DateField(default=datetime.date.today)
    visiting_time = models.TimeField(default=datetime.datetime.now)
    def __str__(self):
        return str(self.visitor_name)



class Service(models.Model):
    service_name=models.CharField(max_length=100)
    service_email=models.EmailField(null=True)
    service_details=models.TextField(blank=True)
    def __str__(self):
        return str(self.service_name)


class Bills(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    repairs_maintenance_charges = models.IntegerField()
    society_service_charges = models.IntegerField()
    sinking_fund_charges = models.IntegerField(default=80)
    parking_charges = models.IntegerField(default=100)
    charity_charges = models.IntegerField(default=20)
    previous_dues = models.IntegerField(default=0, null=True)

    publish_date = models.DateField(default=datetime.date.today, blank=True)
    due_date = models.DateField()
    flat_no_and_date = models.CharField(max_length=100)
    def __str__(self):
        return str(self.flat_no_and_date)

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Complaint, Notice, Service, Visitor
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    age = forms.IntegerField()
    flat_no = forms.CharField(max_length=10, required=True)
    phone_number = forms.IntegerField()

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", 'age', 'flat_no'
                , 'phone_number')
        def save(self, commit=True):
            user =  super(NewUserForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            user.age = self.cleaned_data['age']
            user.flat_no = self.cleaned_data['flat_no']
            user.phone_number = self.cleaned_data['phone_number']
            if commit:
                user.save()
            return user

class otpForm(ModelForm):
    class Meta:
        model = Visitor
        fields = ['otp']
    otp = forms.CharField(required=True)
    def __init__(self, *args, **kwargs):
        super(otpForm, self).__init__(*args, **kwargs)
        self.fields['otp'].label = "Enter the OTP:"

class ComplaintForm(ModelForm):
    class Meta:
        model = Complaint
        fields = ['contact_name', 'contact_email', 'content']


    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(ComplaintForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['content'].label = "Please specify your complaint:"


class NoticeForm(ModelForm):
    class Meta:
        model = Notice
        fields = ['header_notice', 'details_notice']

    header_notice = forms.CharField(required=True)
    details_notice = forms.CharField(required=True,widget=forms.Textarea)


    def __init__(self, *args, **kwargs):
        super(NoticeForm, self).__init__(*args, **kwargs)
        self.fields['header_notice'].label = "Specify the subject:"
        self.fields['details_notice'].label = "Enter the content of the notice:"


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = ['service_name','client','service_details']

    demo_choice = (
                    ("1", "Electrician"),
                    ("2", "Internet Service Provider"),
                    ("3", "Plumber"),
                  )
    service_name = forms.ChoiceField(choices = demo_choice )
    client = forms.CharField(required=True)
    service_details = forms.CharField(required=True,widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
        self.fields['client'].label = "Please enter your Flat Number:"
        self.fields['service_details'].label = "Specify your request:"


class VisitorForm(ModelForm):
    class Meta:
        model = Visitor
        fields = ['visitor_name', 'visitor_phone', 'visiting_flat', 'visiting_date', 'visiting_time']


    visitor_name = forms.CharField(max_length=100, required = True)
    visitor_phone =  forms.IntegerField(required = True)
    visiting_flat = forms.CharField(max_length=100, required = True)
    visiting_date = forms.DateField(required = True)
    visiting_time = forms.TimeField(required = True)

main/templates/main/addvisitor.html
<html><head>

    <link rel="stylesheet" href="/static/tiny/css/prism">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="/static/main/css/materialize.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
          $('select').formSelect();
          $('.datepicker').datepicker();
      })
    </script>

</head>

<body>


<nav>
    <div class="nav-wrapper #1976d2 blue darken-2">
        <a href="/" class="brand-logo">E-House Care</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/">Home</a></li>



                <li><a href="/makenotice">Make Notice</a></li>
                <li><a href="/addvisitor">Add Visitors</a></li>
                <li><a href="/visitor">Visitors Log</a></li>

                <li><a href="/noticeboard">Notice Board</a></li>

                <li><a href="/logout">Logout</a></li>


        </ul>
    </div>
</nav>
<style media="screen">
  a.brand-logo{
    margin-left: 15px;
  }
</style>



    <br><br>
    <div class="container">
<h1 style="text-align:center;">Add Visitors</h1>
<form role="form" action="" method="post">
    {% csrf_token %}
    <p><label for="id_visitor_name">Visitor name:</label> <input type="text" name="visitor_name" maxlength="100" required="" id="id_visitor_name"></p>
<p><label for="id_visitor_phone">Visitor phone:</label> <input type="number" name="visitor_phone" required="" id="id_visitor_phone"></p>
<p><label for="id_visiting_flat">Visiting flat:</label> <input type="text" name="visiting_flat" maxlength="100" required="" id="id_visiting_flat"></p>
<p><label for="id_visiting_date" >Visiting date:</label> <input type="date" class="datepicker" name="visiting_date" required="" id="id_visiting_date"></p>
<p><label for="id_visiting_time">Visiting time:</label> <input type="time" name="visiting_time" required="" id="id_visiting_time"></p>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Submit</button>
</form>

</div>



</body></html>

main/templates/main/complaint.html
{% extends "main/header.html" %} {% block content %}
<h1 style="text-align:center;">Complaint Box</h1>
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn" style='background-color: blanchedalmond; color: brown;'>Submit</button>
</form>

{% endblock %}

main/templates/main/header.html
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'tiny/css/prism' %}" />
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'main/css/materialize.css' %}" />
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
          $('select').formSelect();
      })
    </script>

</head>

<body>
    {% include 'main/includes/nav.html' %}
    {% include 'main/includes/messages.html' %}
    <br /><br />
    <div class="container">{% block content %} {% endblock %}</div>
</body>

<script src="{% static 'tinymce/js/prism.js' %}"></script>

main/templates/main/makenotice.html
{% extends "main/header.html" %} {% block content %}

<h1 style="text-align:center;">Post a Notice</h1>
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn" style='background-color: blanchedalmond; color: brown;'>Post</button>
</form>

{% endblock %}

main/templates/main/noticeboard.html
{% extends "main/header.html" %} {% block content %}




<div class="container">
  <h1 style="text-align:center;">Notice Board</h1>
  {% for notice in noticeboard %}
  <div class="col s12 m6 l4">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">{{notice.header_notice}}</span>
        <p>{{notice.details_notice|safe}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

<style media="screen">
.container{
  position: relative;
  top: 100px;
  left: 100px;
}
h1{text-align: center;}
</style>

main/templates/main/pay.html
{% extends "main/header.html" %}

{% block content %}


<head>
    <style>
        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<div class="center">

    <form class="text-center border border-light p-5"  method="POST">
        {% csrf_token %}

        <h1><p class="h3 mb-3"><i class="fas fa-coffee"></i> Pay {{final}}</p></h1>
        <p class="mb-3">Thanks for the extra donation of ₹20</p>

        {% csrf_token %}
        <button id="pay-btn">Proceed</button>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
            <script>
                    var options = {
                    key: "rzp_test_CK8AWrEy84pP7i",
                    amount: "{{finalP}}",
                    currency: "INR",

                    name: "E-Housing society Bill",

                    order_id: "{{ order_id }}"
                    
                    };
                    
                    var rzp1 = new Razorpay(options);
                    
                    // add event listener to the payment button.
                    document.getElementById("pay-btn").onclick = function (e) {
                    rzp1.open();
                    e.preventDefault();
                    };
                    
            </script>
    </form>

</div>


</div>
{% endblock %}

main/templates/main/pay1.html
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      * {
        box-sizing: border-box;
        padding: 0px;
        margin: 0px;
        font-family: cursive;
      }
      html,
      body {
        height: 100%;
      }
      body {
        background-color: #f1f5f8;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .card {
        background-color: white;
        padding: 25px;
        border: 1px solid #bbbbbb;
        border-radius: 5px;
        box-shadow: 1px 1px 10px 0px rgb(0 0 0 / 25%);
      }
      .title {
        text-align: center;
        letter-spacing: 1px;
      }
      .muted {
        color: #8e7f7f;
        display: block;
        margin-bottom: 10px;
        text-align: center;
      }
      .btn_container {
        padding: 20px;
        text-align: center;
      }
      .btn {
        border-radius: 4px;
        cursor: pointer;
        padding: 4px 8px;
        background-color: #ffaaa7;
        color: white;
        font-size: 1.2em;
        font-weight: 600;
        letter-spacing: 1px;
      }
    </style>
  </head>
  <body>
    <div class="card">
      <h1 class="title">Pay {{final}}</h1>
      <small class="muted"
        >Thanks for the extra donation of ₹20</small
      >
      <div class="btn_container">

        <form method="POST" action="http://127.0.0.1:8000/success">
            {% csrf_token %}
            <button id="pay-btn">Proceed</button>
          
            <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
            <script>
                    var options = {
                    key: "rzp_test_CK8AWrEy84pP7i",
                    amount: "{{finalP}}",
                    currency: "INR",

                    name: "E-Housing society Bill",

                    // Pass the `id` obtained in the response of Step 1
                    order_id: "{{ order_id }}"
                    };
                    };
            </script>
        </form>
      </div>
    </div>
  </body>
   

</html>


{% endblock content %}

main/templates/main/register.html
{% extends "main/header.html" %} {% block content %}
<form action="" method="post">
    {% csrf_token %} {{form.as_p}} <br>
    <button type="submit" class="btn" style='background-color: blanchedalmond; color: brown;'>Submit</button>
</form>

If you already have an account, you can <a href="/login"><strong>login</strong></a> instead. {% endblock %}

main/templates/main/searchbill.html
{% extends "main/header.html" %} {% block content %}



<div class="row">
  {% for main in searchbill %}
  <div class="col s12 m6 l4">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Maintenance Bill</span>
        <p>Published Date: {{main.publish_date}}</p>
        <p>Due Date: {{main.due_date}}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'main:viewbill' main.id %}">View</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

main/templates/main/service.html
<html><head>

    <link rel="stylesheet" href="/static/tiny/css/prism">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="/static/main/css/materialize.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
          $('select').formSelect();
      })
    </script>

</head>

<body>


<nav>
    <div class="nav-wrapper #1976d2 blue darken-2">
        <a href="/" class="brand-logo">E-House Care</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/">Home</a></li>



            {% if user.is_staff %}
              <li><a href="/makenotice">Make Notice</a></li>
            {% endif %}

              <li><a href="/noticeboard">Notice Board</a></li>
              <li><a href="/service">Services</a></li>
              <li><a href="/searchbill">Bills</a></li>
              <li><a href="/complaint">Complaint Box</a></li>
              <li><a href="/staff">Society Staff</a></li>
              <li><a href="/logout">Logout</a></li>

        </ul>
    </div>
</nav>
<style media="screen">
  a.brand-logo{
    margin-left: 15px;
  }
</style>



    <br><br>
    <div class="container">
<h1 style="text-align:center;">Services</h1>
<form role="form" action="" method="post">{% csrf_token %}

    <p><label for="id_service_name">Service name:</label> <select class="browser-default" name="service_name" id="id_service_name">
  <option value="1">Electrician</option>

  <option value="2">Internet Service Provider</option>

  <option value="3">Plumber</option>

</select></p>
<p><label for="id_client" class="">Please enter your Flat Number:</label> <input type="text" name="client" required="" id="id_client"></p>
<p><label for="id_service_details" class="">Specify your request:</label> <textarea name="service_details" cols="40" rows="10" required="" id="id_service_details"></textarea></p>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Request</button>
</form>

</div>


<script src="/static/tinymce/js/prism.js"></script>
</body></html>

main/templates/main/staff.html
{% extends "main/header.html" %} {% block content %}
<h1>Society Staff</h1>
<div class="container">


<div class="row">
  {% for member in staff %}
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <img src="{{ member.image.url }}">
          <span class="card-title"><b>{{ member.designation }}</b></span>
        </div>
        <div class="card-content">
          <p style="text-align:center;">
            <h5 style="text-align:center;">{{ member.staff_name }}</h5>
            <h6 style="text-align:center;">Phone Number: {{ member.staff_phone }}</h6>
            <h6 style="text-align:center;">Email: {{ member.staff_email }}</h6>
            {{ member.about }}
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<style media="screen">
  div.container{
    position: relative;
    text-align: center;
    left: 100px;
  }
  h1{
    text-align: center;
    position: relative;
    right: 60px;
  }
</style>

{% endblock %}

main/templates/main/viewbill.html
{% extends "main/header.html" %} {% block content %}

<head>

    <meta charset="utf-8">

    <!-- Load paper.css for happy printing -->


    <!-- Set page size here: A5, A4 or A3 -->
    <!-- Set also "landscape" if you need -->
    <style>@page {
        size: A4 portrait;
        margin-top: 8px;
        margin-bottom: 10px;
        margin-left: 20px;
    }</style>
    <style>
        /* Three image containers (use 25% for four, and 50% for two, etc) */
        .column {
            float: left;
            padding: 5px;
        }

        /* Clear floats after image containers */
        .row::after {
            content: "";
            clear: both;
            display: table;
        }

        table tbody tr td {
            padding: 2px !important;
            line-height: 1.35 !important;
        }

        @media print {
            .box-body {
                margin-top: 10px !important;
                margin-bottom: 10px;
            }
        }
    </style>

    <script type="text/javascript">
      function printPageArea(areaID){
        var printContent = document.getElementById(areaID);
        var WinPrint = window.open('', '', 'width=900,height=650');
        WinPrint.document.write(printContent.innerHTML);
        WinPrint.document.close();
        WinPrint.focus();
        WinPrint.print();
        WinPrint.close();
    }
    </script>
    <style>
        .center-me {
            font-size: 15px;
            margin: auto;
            height: 10px;
            max-width: 500px;
            margin: 75px auto 40px auto;
            display: flex;
        }
    </style>
</head>
<!-- Set "A5", "A4" or "A3" for class name -->
<!-- Set also "landscape" if you need -->
<body class="A4 portrait">

<!-- Each sheet element should have the class "sheet" -->
<!-- "padding-**mm" is optional: you can set 10, 15, 20 or 25 -->
<section class="sheet" id="content-print">
    <style>
        table {
            /*border-collapse: unset !important;*/
        }
    </style>
<div id="printableArea">
    <div class="box-body" id="box_data" style="display: flex;padding: 5px 10px 0 10px;margin-bottom: -21px;">
        <div style="width: 100%;padding-right: 10px;" class="col-md-12">
            <div class="row">
                <div class="col-lg-4" style="width: 70%;padding-left: 20px;">
                    <h4 style="text-align:center;">MAINTENANCE BILL</h4>
                </div>

            </div>

            <br>




            <table width="100%" border="1">
                <tr style="background: rgba(217,225,242,1.0)">
                    <th class="text-center" colspan="2" style="width: 25%;">Bill To</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Name</th>
                    <th>{{profile.name}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Flat Number</th>
                    <th>{{profile.flat_no}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Email</th>
                    <th>{{profile.email}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Date Published</th>
                    <th>{{bill.publish_date}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Date Due</th>
                    <th>{{bill.due_date}}</th>
                </tr>
            </table>
            <br>
            <table width="100%" border="1px">
                <tr style="background: rgba(217,225,242,1.0);">
                    <th class="text-center">
                        Sr No.
                    </th>
                    <th class="text-center" colspan="3">
                        Particulars
                    </th>
                    <th class="text-center">
                        Amount
                    </th>
                </tr>
                <tbody>

                <tr><td>1</td><td colspan="3">Repairs and Maintenance Fund</td><td>{{bill.repairs_maintenance_charges}}</td></tr>
                <tr><td>2</td><td colspan="3">Society Service Charges</td><td>{{bill.society_service_charges}}</td></tr>
                <tr><td>3</td><td colspan="3">Parking Charges</td><td>{{bill.parking_charges}}</td></tr>
                <tr><td>4</td><td colspan="3">Sinking Fund</td><td>{{bill.sinking_fund_charges}}</td></tr>
                <tr><td>5</td><td colspan="3">Charity Fund</td><td>{{bill.charity_charges}}</td></tr>
                </tbody>



                <tfoot>
                <tr style="background: rgba(217,225,242,1.0);">
                    <td colspan="4">Total Amount</td>
                    <td colspan="1">{{total}}</td>
                </tr>
                <tr>
                  <td colspan="4">Previous Dues (If Any)</td>
                  <td colspan="1">{{bill.previous_dues}}</td>
                </tr>
                <tr style="background: rgba(217,225,242,1.0);">

                    <td colspan="4">Final Amount</td>
                    <td>{{final}}</td>
                </tr>
                </tfoot>


            </table>
            <br>

        </div>

    </div>
</div><br>
<a href="{% url 'main:pay' bill_id %}" class="btn">Pay</a>
<a href="javascript:void(0);" class="btn" onclick="printPageArea('printableArea')">Print</a><br><br>
</section>
</body>
<style media="screen">
  a.btn{
    position:relative;
    left:500px;
  }
  h4{
    position:relative;
    left:150px;
  }
</style>
{% endblock %}

main/templates/main/visitor.html
{% extends "main/header.html" %} {% block content %}
<div class="container">
  <h1 style="text-align:center;">Visitor Log</h1>
  <table border=1>
    <tr>
      <td>Name</td>
      <td>Phone Number</td>
      <td>Visiting Flat</td>
      <td>Date</td>
      <td>Time</td>
    </tr>
    {% for v in visit %}
    <tr>
      <td>{{v.visitor_name}}</td>
      <td>{{v.visitor_phone}}</td>
      <td>{{v.visiting_flat}}</td>
      <td>{{v.visiting_date}}</td>
      <td>{{v.visiting_time}}</td>
    </tr>
    {% endfor %}
  </table>



{% endblock %}

main/templates/main/visitorotp.html
{% extends "main/header.html" %} {% block content %}
Enter the OTP sent to the mobile number
<form role="form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn" style='background-color: blanchedalmond; color: brown;'>Submit</button>
</form>
{% endblock %}